export const SHOW_LOADING = "SHOW_LOADING";
export const HIDE_NOTIFICATION = "HIDE_NOTIFICATION";
export const UPDATE_NOTIFICATION = "UPDATE_NOTIFICATION";
export const UPDATE_SHIPPER = 'UPDATE_SHIPPER';
export const UPDATE_SHIPPER_DETAILS = 'UPDATE_SHIPPER_DETAILS';
export const UPDATE_RANDOM_QUOTES = 'UPDATE_RANDOM_QUOTES';
export const UPDATE_AUTHOR_QUOTES = 'UPDATE_AUTHOR_QUOTES';